<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.akka</groupId>
    <artifactId>akka-javasdk-parent</artifactId>
    <version>3.5.3</version>
  </parent>
  
  <groupId>com.example.akka</groupId>
  <artifactId>fintech-workshop</artifactId>
  <version>1.0.2</version>
  <packaging>pom</packaging>

  <name>fintech-workshop</name>

  <properties>
    <jib.version>3.4.0</jib.version>
    <docker.registry>docker.io</docker.registry>
    <docker.organization>samirachoscalac</docker.organization>
    <docker.tag>${project.version}</docker.tag>
  </properties>

  <dependencies>
    <!-- Your dependencies go here -->
  </dependencies>
  <modules>
    <module>api</module>
    <module>payments</module>
    <module>corebanking</module>
    <module>backoffice</module>
  </modules>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>com.google.cloud.tools</groupId>
          <artifactId>jib-maven-plugin</artifactId>
          <version>${jib.version}</version>
          <configuration>
            <from>
              <image>eclipse-temurin:21-jre@sha256:615497e30ae2b2654ff7bccc7cb057c27443041994593c726852f04dc99830b1</image>
            </from>
            <to>
              <image>${docker.registry}/${docker.organization}/akka-demo:${project.artifactId}-${docker.tag}</image>
            </to>
            <container>
                <mainClass>akka.runtime.AkkaRuntimeMain</mainClass>
                <ports>
                    <port>8080</port>
                </ports>
            </container>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
  
  <repositories>
    <repository>
      <id>akka-secure</id>
      <name>Akka Secure</name>
  <url>https://repo.akka.io/${env.AKKA_REPO_TOKEN}/secure</url>
    </repository>
  </repositories>

  <pluginRepositories>
        <pluginRepository>
        <id>akka-plugin-repository</id>
  <url>https://repo.akka.io/${env.AKKA_REPO_TOKEN}/secure</url>
        </pluginRepository>
  </pluginRepositories>

</project>
